"""Run the test suite under ``coverage.py`` and enforce the 90% floor.

Coverage for subprocess-invoked scripts is tricky. This runner uses
``coverage.py``'s subprocess-tracing feature, which requires three
things to line up:

1. A ``.coveragerc`` with ``parallel = True``, ``source`` pointing at an
   absolute path to ``scripts/``, and ``data_file`` pointing at
   ``.coverage_data/.coverage`` (an absolute path). All transient
   ``.coverage.<pid>`` files land under ``.coverage_data/`` instead of
   the repo root.
2. A ``sitecustomize.py`` installed into the active venv's
   ``site-packages`` directory that calls ``coverage.process_startup()``.
   (Python's ``site`` startup only picks up ``sitecustomize`` from
   ``site-packages``, not from ``PYTHONPATH``.)
3. ``COVERAGE_PROCESS_START`` in the environment pointing at the
   ``.coveragerc`` file. This env var is what ``process_startup`` reads
   to decide whether to start tracing and what config to use.

After pytest finishes, ``coverage.Coverage.combine`` merges every
per-process data file into the parent's and the final line-coverage
report runs. ``keep=False`` deletes the per-pid files as they are
combined, so ``.coverage_data/`` ends the run with just one file.

Runtime under ``scripts/`` stays stdlib-only; everything here is
dev-time only.
"""

from __future__ import annotations

import os
import pathlib
import site
import sys

FAIL_UNDER = 90.0

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
COVERAGERC = REPO_ROOT / ".coveragerc"


# Must be silent — subprocess-level prints to stderr break integration
# tests that parse stderr as an Error_Envelope JSON.
_SITECUSTOMIZE_CONTENT = """\
# Auto-generated by tests/coverage_runner.py. Safe to delete; regenerated
# on every `make test` run.
try:
    import coverage  # type: ignore[import-not-found]
    coverage.process_startup()
except ImportError:
    pass
"""


_COVERAGERC_CONTENT = """\
# Auto-generated by tests/coverage_runner.py. Regenerated on every `make test`.
[run]
source = {scripts_abs}
# Absolute path under a dedicated .coverage_data/ subdir. Keeps the
# hundreds of transient .coverage.<pid> files subprocesses create out
# of the repo root, and guarantees they land here even when the
# subprocess runs from a temp cwd (which tests clean up).
data_file = {data_file}
parallel = True
branch = False
omit =
    */__init__.py

[report]
exclude_lines =
    pragma: no cover
    if __name__ == .__main__.:
    raise NotImplementedError
show_missing = True
skip_empty = True
"""


def _site_packages() -> pathlib.Path | None:
    """Return the writable site-packages dir for the current interpreter."""
    paths = site.getsitepackages()
    if not paths:
        return None
    return pathlib.Path(paths[0])


def _write_config_files() -> None:
    sp = _site_packages()
    if sp is None or not sp.is_dir():
        print(
            "error: could not find site-packages. Is the venv active?",
            file=sys.stderr,
        )
        raise SystemExit(2)
    (sp / "sitecustomize.py").write_text(_SITECUSTOMIZE_CONTENT, encoding="utf-8")
    # Absolute paths throughout so subprocesses with a different cwd
    # (integration tests running from a temp App_Root) still match AND
    # still write their per-pid data files into this repo's .coverage_data/
    # dir rather than the temp cwd (which tests clean up, taking the data
    # with them). The dedicated dir also keeps hundreds of transient
    # .coverage.<pid> files out of the repo root.
    scripts_abs = (REPO_ROOT / "scripts").resolve()
    data_dir = REPO_ROOT / ".coverage_data"
    data_dir.mkdir(parents=True, exist_ok=True)
    data_file = data_dir / ".coverage"
    rc_content = _COVERAGERC_CONTENT.format(scripts_abs=scripts_abs, data_file=data_file)
    COVERAGERC.write_text(rc_content, encoding="utf-8")


def _wipe_stale_data() -> None:
    data_dir = REPO_ROOT / ".coverage_data"
    if data_dir.exists():
        for stale in data_dir.iterdir():
            if stale.is_file():
                stale.unlink()
    # Legacy root-level files from older runs.
    for stale in REPO_ROOT.glob(".coverage.*"):
        if stale.is_file():
            stale.unlink()
    legacy = REPO_ROOT / ".coverage"
    if legacy.is_file():
        legacy.unlink()


def _main() -> int:
    try:
        import coverage  # noqa: PLC0415
        import pytest  # noqa: PLC0415
    except ImportError:
        print(
            "coverage / pytest not installed in this environment. "
            "Install `requirements-dev.txt` locally.",
            file=sys.stderr,
        )
        return 2

    _write_config_files()
    _wipe_stale_data()

    # Tell subprocesses to auto-trace themselves.
    os.environ["COVERAGE_PROCESS_START"] = str(COVERAGERC)

    cov = coverage.Coverage(config_file=str(COVERAGERC))
    cov.start()
    try:
        extra_args = sys.argv[1:]
        # If the caller passed explicit test paths, use those; otherwise
        # default to the full tests/ tree.
        pytest_args = extra_args if extra_args else [str(REPO_ROOT / "tests")]
        rc = pytest.main(pytest_args)
    finally:
        cov.stop()
        cov.save()
        # Merge every .coverage.<pid> written by subprocesses into the
        # parent data file.
        try:
            cov.combine(strict=False, keep=False)
            cov.save()
        except coverage.exceptions.CoverageException:
            # No subprocess data to merge; the parent's data file is fine.
            pass

    print()
    print("Coverage report (line):")
    pct = cov.report(show_missing=True, skip_empty=True)

    if rc != 0:
        print(f"\npytest exited with code {rc}", file=sys.stderr)
        return int(rc)
    if pct < FAIL_UNDER:
        print(
            f"\nLine coverage {pct:.1f}% is under the {FAIL_UNDER:.0f}% threshold.",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
