"""One-shot helper: dump `db/datasource.db` DDL to `tests/fixtures/schema.sql`.

Run once from the repo root whenever the real DB's schema changes:

    python tests/fixtures/dump_schema.py

The resulting `tests/fixtures/schema.sql` is what `tests/integration/conftest.py`
applies to the per-test temp DB. This script opens the real DB read-only (SQLite
URI `mode=ro`) so it cannot modify `db/datasource.db` under any circumstance.

The dumped file is deterministic: tables, then indexes, then triggers/views,
each group sorted by name. Internal SQLite objects (names starting with
`sqlite_`) are skipped.
"""

from __future__ import annotations

import pathlib
import sqlite3
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
REAL_DB = REPO_ROOT / "db" / "datasource.db"
OUT_FILE = pathlib.Path(__file__).resolve().parent / "schema.sql"

_ORDER = {"table": 0, "index": 1, "view": 2, "trigger": 3}


def _fetch_ddl(conn: sqlite3.Connection) -> list[tuple[str, str, str]]:
    """Return a list of `(type, name, sql)` tuples sorted by type then name."""
    rows = conn.execute(
        "SELECT type, name, sql FROM sqlite_master "
        "WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' "
        "ORDER BY type, name"
    ).fetchall()
    return sorted(
        [(t, n, s) for t, n, s in rows],
        key=lambda r: (_ORDER.get(r[0], 99), r[1]),
    )


def main() -> int:
    if not REAL_DB.exists():
        print(f"real DB not found at {REAL_DB}", file=sys.stderr)
        return 1

    # Read-only URI open. Even a buggy version of this script cannot write
    # to the real DB through this connection.
    uri = f"file:{REAL_DB}?mode=ro"
    conn = sqlite3.connect(uri, uri=True)
    try:
        ddl = _fetch_ddl(conn)
    finally:
        conn.close()

    lines: list[str] = [
        "-- Auto-generated by tests/fixtures/dump_schema.py.",
        "-- Do not edit by hand. Regenerate via `python tests/fixtures/dump_schema.py`.",
        "",
    ]
    for kind, name, sql in ddl:
        lines.append(f"-- {kind}: {name}")
        # Ensure each DDL ends with a semicolon + blank line.
        stmt = sql.strip().rstrip(";") + ";"
        lines.append(stmt)
        lines.append("")

    OUT_FILE.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT_FILE.relative_to(REPO_ROOT)} ({len(ddl)} objects)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
