-- Auto-generated by tests/fixtures/dump_schema.py.
-- Do not edit by hand. Regenerate via `python tests/fixtures/dump_schema.py`.

-- table: artist
CREATE TABLE "artist" (
	"id"	TEXT,
	"name"	TEXT NOT NULL,
	"name_context"	TEXT DEFAULT '',
	"created_at"	INTEGER,
	"updated_at"	INTEGER,
	"status"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("id")
);

-- table: learning
CREATE TABLE "learning" (
	"id" TEXT PRIMARY KEY,
	"song_id" TEXT NOT NULL,
	"level" INTEGER NOT NULL DEFAULT 0,
	"created_at" INTEGER NOT NULL,
	"updated_at" INTEGER NOT NULL,
	"last_level_up_at" INTEGER NOT NULL,
	"level_up_path" TEXT NOT NULL,
	"graduated" INTEGER NOT NULL DEFAULT 0, -- * 0: wip, 1: graduated
	FOREIGN KEY("song_id") REFERENCES "song"("id")
);

-- table: play_history
CREATE TABLE "play_history" (
	"id"	TEXT,
	"show_id"	TEXT NOT NULL,
	"song_id"	TEXT NOT NULL,
	"created_at"	INTEGER NOT NULL,
	"media_url"	TEXT DEFAULT '',
	"status"	INTEGER DEFAULT 0,
	PRIMARY KEY("id")
);

-- table: rel_show_song
CREATE TABLE "rel_show_song" (
	"show_id"	TEXT NOT NULL,
	"song_id"	TEXT NOT NULL,
	"media_url"	TEXT,
	"created_at"	INTEGER,
	CONSTRAINT "unique_song_show_rel_show_song" UNIQUE("show_id","song_id"),
	FOREIGN KEY("song_id") REFERENCES "song"("id") ON DELETE CASCADE,
	FOREIGN KEY("show_id") REFERENCES "show"("id") ON DELETE CASCADE
);

-- table: show
CREATE TABLE "show" (
	"id"	TEXT,
	"name"	TEXT NOT NULL,
	"name_romaji"	TEXT,
	"vintage"	TEXT,
	"s_type"	TEXT,
	"created_at"	INTEGER,
	"updated_at"	INTEGER,
	"status"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("id")
);

-- table: song
CREATE TABLE song (
	id TEXT PRIMARY KEY,
	name TEXT NOT NULL,
	name_context TEXT DEFAULT "",
	artist_id TEXT NOT NULL,
	created_at INTEGER,
	updated_at INTEGER,
	status INTEGER NOT NULL DEFAULT 0 -- * 0: normal, 1: deleted
);

-- index: idx_learning_song_id
CREATE INDEX idx_learning_song_id ON learning(song_id);

-- index: idx_rel_show_song_show_id
CREATE INDEX idx_rel_show_song_show_id on rel_show_song(show_id);

-- index: idx_rel_show_song_song_id
CREATE INDEX idx_rel_show_song_song_id on rel_show_song(song_id);
